### ISSUE TITLE
error to open it

### ISSUE THREAD

**Issue by x1aohu2003** [AlexIII/tcc-g15#26]
Traceback (most recent call last):
  File "tcc-g15.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "GUI\AppGUI.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "Backend\AWCCThermal.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "Backend\AWCCWmiWrapper.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "wmi.py", line 174, in <module>
  File "win32com\client\__init__.py", line 85, in GetObject
  File "win32com\client\__init__.py", line 102, in Moniker
pywintypes.com_error: (-2147023838, '无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。', None, None)

**Comment by x1aohu2003** [comment]
sorry, I download the wrong version. my PC is 5510
