### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by z0z0r4** [AlexIII/tcc-g15#44]
My device is G3 3950, Windows 11
```
Processor	Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	6519C5F6-33DB-4105-9D7E-63AD5BFC2D0C
Product ID	00330-80000-00000-AA790
System type	64-bit operating system, x64-based processor

Edition	Windows 11 Pro
Version	23H2
Installed on	‎10/‎15/‎2022
OS build	22631.4169
Experience	Windows Feature Experience Pack 1000.22700.1034.0

```
Until last month I could still launch the software...but this week it started giving me errors without updating

After updating it still gave me errors

G3 is no longer supported?
```
Traceback (most recent call last):
  File "wmi.py", line 456, in __call__
  File "<COMObject <unknown>>", line 2, in ExecMethod_
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'SWbemObjectEx', 'Generic failure ', None, 0, -2147217407), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tcc-g15.py", line 35, in <module>
  File "tcc-g15.py", line 31, in main
  File "GUI\AppGUI.py", line 458, in runApp
  File "GUI\AppGUI.py", line 277, in __init__
  File "GUI\AppGUI.py", line 267, in onModeChange
  File "Backend\AWCCThermal.py", line 66, in setMode
  File "Backend\AWCCWmiWrapper.py", line 76, in ApplyThermalMode
  File "Backend\AWCCWmiWrapper.py", line 91, in _Thermal_Control
  File "Backend\AWCCWmiWrapper.py", line 96, in _call
  File "wmi.py", line 473, in __call__
  File "wmi.py", line 258, in handle_com_error
wmi.x_wmi: <x_wmi: Unexpected COM Error (-2147352567, 'Exception occurred.', (0, 'SWbemObjectEx', 'Generic failure ', None, 0, -2147217407), None)>
```

**Comment by z0z0r4** [comment]
tcc-g15 version is 9.0.1

**Comment by AlexIII** [comment]
Hi! We don't have version `9.0.1`. There was no changes regarding support of the laptop models. The error you've posted says that the program cannot access dell WMI interface. Can be due to various reasons: dell software or some system update. Only thing I can recommend is reinstalling dell awcc software (it has the necessary drivers which it should install along the way).

**Comment by z0z0r4** [comment]
I am sorry that it is 1.6.0

OK, Let me try to reinstall AWCC
